{
 "title": "go-waku-monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": "label_values({job=\"postgres-exporter\"}, instance)"
   },
   { "name": "Database", "query": "label_values(datname)" },
   { "name": "Interval", "query": "30sec,1m,10m,30m,1h,6h,12h,1d" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Waku Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reachability Status",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "libp2p_autonat_reachability_status",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Reachability status confidence",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_autonat_reachability_status_confidence",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Peers ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "waku_connected_peers", "legendFormat": "{{direction}}_{{protocol}}" }
   ]
  },
  {
   "title": "Start Time (UTC)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"go-waku\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discv5 (Nodes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "routing_table_nodes", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "waku_version{instance=\"go-waku:8003\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discv5 (Seen Nodes)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "routing_table_nodes{state=\"seen\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number Pubsub Topics",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "waku_pubsub_topics", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Message distrubution %/kBytes (Last Hour)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(waku_histogram_message_size_bucket[1h])/scalar(rate(waku_histogram_message_size_count[1h]))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Msg Size (Last Hour)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(waku_histogram_message_size_sum[1h])/rate(waku_histogram_message_size_count[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "75% Percentile (Last hour)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, rate(waku_histogram_message_size_bucket[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99% Percentile (Last Hour)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(waku_histogram_message_size_bucket[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages/second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "(increase(waku_node_messages[1m]))/60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average msg size (kBytes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "waku_histogram_message_size_sum/waku_histogram_message_size_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Peer Store Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "waku_peer_store_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_rcmgr_peer_connections_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "libp2p traffic (in)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(libp2p_network_bytes_total{direction=\"in\"}[$__rate_interval])",
     "legendFormat": "traffic_{{direction}}"
    }
   ]
  },
  {
   "title": "libp2p traffic (out)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(libp2p_network_bytes_total{direction=\"out\"}[$__rate_interval])",
     "legendFormat": "traffic_{{direction}}"
    }
   ]
  },
  {
   "title": "RLN Proof Generation (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "waku_rln_proof_generation_duration_seconds_sum",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "RLN Proof Verification (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 28 },
   "targets": [
    {
     "expr": "waku_rln_proof_verification_duration_seconds_sum",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "RLN Registered Memberships",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "waku_rln_number_registered_memberships",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "RLN Credentials Import (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "waku_rln_membership_credentials_import_duration_seconds",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "RLN Proof Verification Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 34 },
   "targets": [
    {
     "expr": "waku_rln_proof_verification_total",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "RLN Membership Insertion (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "waku_rln_membership_insertion_duration_seconds",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "RLN Messages Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 40 },
   "targets": [
    { "expr": "waku_rln_messages_total", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "RLN Invalid Messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 40 },
   "targets": [
    {
     "expr": "waku_rln_invalid_messages_total",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "RLN Spam Messages Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 40 },
   "targets": [
    { "expr": "waku_rln_spam_messages_total", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Heap allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_heap_alloc_bytes{}", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Go Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes{}", "legendFormat": "{{__name__}}" }
   ]
  },
  { "title": "Postgres", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "PostgreSQL Version",
   "type": "stat",
   "description": "Source: server_version_num",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 55 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_settings_server_version_num)"
    }
   ]
  },
  {
   "title": "Max Replication Lag (Postgres)",
   "type": "stat",
   "description": "Max Replication lag behind master in seconds\n\nOnly available on a standby system.\n\nSource: pg_last_xact_replay_timestamp\n\nUse: pg_stat_replication for Details.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 55 },
   "format": "s",
   "valueName": "max",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_replication_lag{instance=\"$Instance\"})"
    }
   ]
  },
  {
   "title": "Average query runtime (Postgres)",
   "type": "stat",
   "description": "Source: pg_stat_statements.total_time / pg_stat_statements.calls",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 55 },
   "format": "s",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((delta(pg_stat_statements_total_time_seconds{instance=\"$Instance\"}[$Interval])))/sum((delta(pg_stat_statements_calls{instance=\"$Instance\"}[$Interval])))"
    }
   ]
  },
  {
   "title": "Shared Buffer Hits (Postgres)",
   "type": "gauge",
   "description": "Shared buffer hits vs reads from disc",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit{instance=~\"$Instance\"})/(sum(pg_stat_database_blks_hit{instance=~\"$Instance\"})+sum(pg_stat_database_blks_read{instance=~\"$Instance\"}))*100"
    }
   ]
  },
  {
   "title": "Connections used (Postgres)",
   "type": "gauge",
   "description": "Percentage of max_connections used",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends)/max(pg_settings_max_connections)"
    }
   ]
  },
  {
   "title": "Commit Ratio (Postgres)",
   "type": "gauge",
   "description": "Transaction committed vs rollbacked",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_xact_commit{instance=\"$Instance\"})/(sum(pg_stat_database_xact_commit{instance=\"$Instance\"}) + sum(pg_stat_database_xact_rollback{instance=\"$Instance\"}))"
    }
   ]
  },
  {
   "title": "Total database size (Postgres)",
   "type": "stat",
   "description": "Size of all databases in $Instance.\n\nSource: pg_database_size()",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "format": "bytes",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_database_size_bytes{instance=\"$Instance\"})"
    }
   ]
  },
  {
   "title": "Transaction rate (Postgres)",
   "type": "stat",
   "description": "Transactions committed + roolback per minute\n\nSource: pg_stat_database,xact_commit + xact_rollback",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 58 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_xact_commit{instance=\"$Instance\"}[$Interval])))+sum((rate(pg_stat_database_xact_rollback{instance=\"$Instance\"}[$Interval])))"
    }
   ]
  },
  {
   "title": "Active clients (Postgres)",
   "type": "stat",
   "description": "Clients executing Statements.\n\nSource: pg_stat_activity",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 58 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"active\",instance=\"$Instance\"})"
    }
   ]
  },
  {
   "title": "Postgres start time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_postmaster_start_time_seconds*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query rate (Postgres)",
   "type": "stat",
   "description": "Statements executed per Minute.\n\nSource: pg_stat_statements.calls",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 61 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((rate(pg_stat_statements_calls{instance=\"$Instance\"}[$Interval])))"
    }
   ]
  },
  {
   "title": "Connections by database (stacked) (Postgres)",
   "type": "graph",
   "description": "View: pg_stat_activity",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (pg_stat_activity_count{instance=\"$Instance\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Connections by state (stacked) (Postgres)",
   "type": "graph",
   "description": "View: pg_stat_activity",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (state) (pg_stat_activity_count{instance=\"$Instance\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Tuples inserts/updates/deletes (Postgres)",
   "type": "graph",
   "description": "Source: pg_stat_database",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_tup_inserted{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum((rate(pg_stat_database_tup_updated{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum((rate(pg_stat_database_tup_deleted{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "Transactions (Postgres)",
   "type": "graph",
   "description": "1 Minute rate of transactions committed or rollback.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum ((rate(pg_stat_database_xact_commit[$Interval])))",
     "legendFormat": "committed"
    },
    {
     "expr": "sum ((rate(pg_stat_database_xact_rollback[$Interval])))",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "Tuples fetched/returned (Postgres)",
   "type": "graph",
   "description": "Source: pg_stat_database\n\n* tup_fetched: rows needed to satisfy queries\n* tup_returned: rows read/scanned",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_tup_fetched{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum((rate(pg_stat_database_tup_returned{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "Returned"
    }
   ]
  },
  {
   "title": "I/O Read/Write time (Postgres)",
   "type": "graph",
   "description": "* blk_read_time: Time spent reading data file blocks by backends in this database, in milliseconds\n* blk_write_time: Time spent writing data file blocks by backends in this database, in milliseconds\n\ntrack_io_timings needs to be activated",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum ((rate(pg_stat_database_blk_read_time{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "blk_read_time"
    },
    {
     "expr": "sum ((rate(pg_stat_database_blk_write_time{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "blk_read_time"
    }
   ]
  },
  {
   "title": "Deadlocks by database (Postgres)",
   "type": "graph",
   "description": "Should be 0 \n\nSource: pg_stat_database\n\nWith log_lock_waits turned on, deadlocks will be logged to the PostgreSQL Logfiles.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) ((rate(pg_stat_database_deadlocks{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Locks by state (Postgres)",
   "type": "graph",
   "description": "Source: pg_locks",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (pg_locks_count{instance=\"$Instance\"})",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Temporary files by database (Postgres)",
   "type": "graph",
   "description": "Should be 0. If temporary files are created, it can indicate insufficient work_mem. With log_temp_files the creation of temporary files are logged to the PostgreSQL Logfiles.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) ((rate(pg_stat_database_temp_files{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Replication lag (Postgres)",
   "type": "graph",
   "description": "Lag behind master in seconds.\n\nOnly available on a standby System.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(pg_replication_lag{instance=\"$Instance\"})",
     "legendFormat": "lag "
    }
   ]
  }
 ]
}