global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "Monitoring"

scrape_configs:
  - job_name: "go-waku"
    static_configs:
    - targets: ["go-waku:8003"]

  - job_name: postgres-exporter
    static_configs:
    - targets: ['postgres-exporter:9187']
